# Generated by Django 3.0.4 on 2020-04-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_days_ref'),
    ]

    operations = [
        migrations.DeleteModel(
            name='days_ref',
        ),
    ]
