# Generated by Django 3.0.4 on 2020-04-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_days_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='sem_sections',
            fields=[
                ('sem_section', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
