# Generated by Django 3.0.4 on 2020-04-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_time_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='time_table',
            constraint=models.UniqueConstraint(fields=('sem_section', 'day_name', 'hour_no'), name='Allotment_check'),
        ),
    ]
