# Generated by Django 3.0.4 on 2020-04-16 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20200413_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('recurrences', recurrence.fields.RecurrenceField()),
                ('day_name', models.ForeignKey(db_column='days_ref', on_delete=django.db.models.deletion.CASCADE, to='accounts.days_ref')),
                ('hour_no', models.ForeignKey(db_column='hour_no', on_delete=django.db.models.deletion.CASCADE, to='accounts.hours')),
                ('sem_section', models.ForeignKey(db_column='sem_section', on_delete=django.db.models.deletion.CASCADE, to='accounts.sem_sections')),
                ('subject_id', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.subjects')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
