# Generated by Django 3.0.4 on 2020-04-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
