# Generated by Django 3.0.4 on 2020-05-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200416_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tt_record',
        ),
    ]
