# Generated by Django 3.0.4 on 2020-05-06 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_delete_tt_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='tt_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rescheduled', models.BooleanField(default=False)),
                ('is_populated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('day_name', models.ForeignKey(db_column='days_ref', on_delete=django.db.models.deletion.CASCADE, to='accounts.days_ref')),
                ('hour_no', models.ForeignKey(db_column='hour_no', on_delete=django.db.models.deletion.CASCADE, to='accounts.hours')),
                ('sem_section', models.ForeignKey(db_column='sem_section', on_delete=django.db.models.deletion.CASCADE, to='accounts.sem_sections')),
                ('subject_id', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.subjects')),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.time_table')),
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tt_record',
            constraint=models.UniqueConstraint(fields=('username', 'subject_id', 'sem_section', 'day_name', 'hour_no', 'date'), name='Record_check'),
        ),
    ]
