# Generated by Django 3.0.4 on 2020-05-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200506_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tt_record',
        ),
    ]
