# Generated by Django 3.0.4 on 2020-05-06 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_tt_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='tt_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rescheduled', models.BooleanField(default=False)),
                ('is_populated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.time_table')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tt_record',
            constraint=models.UniqueConstraint(fields=('time_table', 'date'), name='Record_check'),
        ),
    ]
