# Generated by Django 3.0.4 on 2020-05-06 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200506_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tt_record',
            name='time_table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.time_table'),
        ),
    ]
