# Generated by Django 3.0.4 on 2020-05-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200506_1836'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tt_record',
            name='Record_check',
        ),
    ]
