# Generated by Django 3.0.4 on 2020-05-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200515_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tt_record',
            name='date',
            field=models.DateField(),
        ),
    ]
