# Generated by Django 3.0.4 on 2020-05-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200515_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tt_record',
        ),
    ]
