# Generated by Django 3.0.4 on 2020-05-15 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_delete_tt_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='tt_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_rescheduled', models.BooleanField(default=False)),
                ('is_populated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('tt', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.time_table')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tt_record',
            constraint=models.UniqueConstraint(fields=('tt_id', 'date'), name='Record_check'),
        ),
    ]
