# Generated by Django 3.0.4 on 2020-05-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200515_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tt_record',
            name='tt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tt_id_value', to='accounts.time_table'),
        ),
    ]
