# Generated by Django 3.0.4 on 2020-07-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20200515_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tt_record',
        ),
    ]
