# Generated by Django 3.0.4 on 2020-07-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20200703_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tt_record',
        ),
    ]
