# Generated by Django 3.0.4 on 2020-07-03 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0033_delete_tt_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='rescheduled_classes',
            fields=[
                ('rescheduled_id', models.AutoField(primary_key=True, serialize=False)),
                ('resc_date', models.DateField()),
                ('resc_day_name', models.ForeignKey(db_column='days_ref', on_delete=django.db.models.deletion.CASCADE, to='accounts.days_ref')),
                ('resc_hour_no', models.ForeignKey(db_column='hour_no', on_delete=django.db.models.deletion.CASCADE, to='accounts.hours')),
                ('resc_sem_section', models.ForeignKey(db_column='sem_section', on_delete=django.db.models.deletion.CASCADE, to='accounts.sem_sections')),
                ('resc_subject_id', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.subjects')),
                ('resc_username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tt_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_rescheduled', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_absent', models.BooleanField(default=False)),
                ('topic_discussed', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, help_text='Leave Blank if not Applicable', max_length=30)),
                ('date', models.DateField()),
                ('rescheduled_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.rescheduled_classes')),
                ('tt', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tt_id_value', to='accounts.time_table')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tt_record',
            constraint=models.UniqueConstraint(fields=('tt_id', 'date'), name='Record_check'),
        ),
        migrations.AddConstraint(
            model_name='rescheduled_classes',
            constraint=models.UniqueConstraint(fields=('resc_sem_section', 'resc_day_name', 'resc_hour_no'), name='RESC_Allotment_check'),
        ),
    ]
